/*
* Copyright (C) Sportradar AG. See LICENSE for full license governing this code
*/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

namespace Sportradar.OddsFeed.SDK.Messages.Feed
{
    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class odds_change
    {
        private string event_idField;

        private int odds_change_reasonField;

        private bool odds_change_reasonFieldSpecified;

        private oddsGenerationProperties odds_generation_propertiesField;

        private odds_changeOdds oddsField;

        private int productField;

        private long request_idField;

        private bool request_idFieldSpecified;

        private sportEventStatus sport_event_statusField;

        private long timestampField;

        /// <remarks />
        public sportEventStatus sport_event_status
        {
            get => sport_event_statusField;
            set => sport_event_statusField = value;
        }

        /// <remarks />
        public oddsGenerationProperties odds_generation_properties
        {
            get => odds_generation_propertiesField;
            set => odds_generation_propertiesField = value;
        }

        /// <remarks />
        public odds_changeOdds odds
        {
            get => oddsField;
            set => oddsField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int product
        {
            get => productField;
            set => productField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string event_id
        {
            get => event_idField;
            set => event_idField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public long timestamp
        {
            get => timestampField;
            set => timestampField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public long request_id
        {
            get => request_idField;
            set => request_idField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool request_idSpecified
        {
            get => request_idFieldSpecified;
            set => request_idFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int odds_change_reason
        {
            get => odds_change_reasonField;
            set => odds_change_reasonField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool odds_change_reasonSpecified
        {
            get => odds_change_reasonFieldSpecified;
            set => odds_change_reasonFieldSpecified = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    public class sportEventStatus
    {
        private int away_batterField;

        private bool away_batterFieldSpecified;

        private int away_dismissalsField;

        private bool away_dismissalsFieldSpecified;

        private int away_gamescoreField;

        private bool away_gamescoreFieldSpecified;

        private int away_legscoreField;

        private bool away_legscoreFieldSpecified;

        private int away_penalty_runsField;

        private bool away_penalty_runsFieldSpecified;

        private int away_penalty_scoreField;

        private bool away_penalty_scoreFieldSpecified;

        private int away_remaining_bowlsField;

        private bool away_remaining_bowlsFieldSpecified;

        private decimal away_scoreField;

        private bool away_scoreFieldSpecified;

        private int away_suspendField;

        private bool away_suspendFieldSpecified;

        private int ballsField;

        private bool ballsFieldSpecified;

        private string basesField;

        private clockType clockField;

        private int current_ct_teamField;

        private bool current_ct_teamFieldSpecified;

        private int current_endField;

        private bool current_endFieldSpecified;

        private int current_serverField;

        private bool current_serverFieldSpecified;

        private int deliveryField;

        private bool deliveryFieldSpecified;

        private bool expedite_modeField;

        private bool expedite_modeFieldSpecified;

        private int home_batterField;

        private bool home_batterFieldSpecified;

        private int home_dismissalsField;

        private bool home_dismissalsFieldSpecified;

        private int home_gamescoreField;

        private bool home_gamescoreFieldSpecified;

        private int home_legscoreField;

        private bool home_legscoreFieldSpecified;

        private int home_penalty_runsField;

        private bool home_penalty_runsFieldSpecified;

        private int home_penalty_scoreField;

        private bool home_penalty_scoreFieldSpecified;

        private int home_remaining_bowlsField;

        private bool home_remaining_bowlsFieldSpecified;

        private decimal home_scoreField;

        private bool home_scoreFieldSpecified;

        private int home_suspendField;

        private bool home_suspendFieldSpecified;

        private int inningsField;

        private bool inningsFieldSpecified;

        private int match_statusField;

        private int outsField;

        private bool outsFieldSpecified;

        private int overField;

        private bool overFieldSpecified;

        private periodScoreType[] period_scoresField;

        private int positionField;

        private bool positionFieldSpecified;

        private int possessionField;

        private bool possessionFieldSpecified;

        private int remaining_redsField;

        private bool remaining_redsFieldSpecified;

        private int reportingField;

        private bool reportingFieldSpecified;

        private resultType[] resultsField;

        private statisticsType statisticsField;

        private int statusField;

        private int strikesField;

        private bool strikesFieldSpecified;

        private int throwField;

        private bool throwFieldSpecified;

        private bool tiebreakField;

        private bool tiebreakFieldSpecified;

        private int tryField;

        private bool tryFieldSpecified;

        private int visitField;

        private bool visitFieldSpecified;

        private int yardsField;

        private bool yardsFieldSpecified;

        /// <remarks />
        public clockType clock
        {
            get => clockField;
            set => clockField = value;
        }

        /// <remarks />
        [XmlArrayItem("period_score", IsNullable = false)]
        public periodScoreType[] period_scores
        {
            get => period_scoresField;
            set => period_scoresField = value;
        }

        /// <remarks />
        [XmlArrayItem("result", IsNullable = false)]
        public resultType[] results
        {
            get => resultsField;
            set => resultsField = value;
        }

        /// <remarks />
        public statisticsType statistics
        {
            get => statisticsField;
            set => statisticsField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int status
        {
            get => statusField;
            set => statusField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int reporting
        {
            get => reportingField;
            set => reportingField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool reportingSpecified
        {
            get => reportingFieldSpecified;
            set => reportingFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int match_status
        {
            get => match_statusField;
            set => match_statusField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public decimal home_score
        {
            get => home_scoreField;
            set => home_scoreField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool home_scoreSpecified
        {
            get => home_scoreFieldSpecified;
            set => home_scoreFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public decimal away_score
        {
            get => away_scoreField;
            set => away_scoreField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool away_scoreSpecified
        {
            get => away_scoreFieldSpecified;
            set => away_scoreFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int home_penalty_score
        {
            get => home_penalty_scoreField;
            set => home_penalty_scoreField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool home_penalty_scoreSpecified
        {
            get => home_penalty_scoreFieldSpecified;
            set => home_penalty_scoreFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int away_penalty_score
        {
            get => away_penalty_scoreField;
            set => away_penalty_scoreField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool away_penalty_scoreSpecified
        {
            get => away_penalty_scoreFieldSpecified;
            set => away_penalty_scoreFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int home_gamescore
        {
            get => home_gamescoreField;
            set => home_gamescoreField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool home_gamescoreSpecified
        {
            get => home_gamescoreFieldSpecified;
            set => home_gamescoreFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int away_gamescore
        {
            get => away_gamescoreField;
            set => away_gamescoreField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool away_gamescoreSpecified
        {
            get => away_gamescoreFieldSpecified;
            set => away_gamescoreFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int home_legscore
        {
            get => home_legscoreField;
            set => home_legscoreField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool home_legscoreSpecified
        {
            get => home_legscoreFieldSpecified;
            set => home_legscoreFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int away_legscore
        {
            get => away_legscoreField;
            set => away_legscoreField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool away_legscoreSpecified
        {
            get => away_legscoreFieldSpecified;
            set => away_legscoreFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int current_server
        {
            get => current_serverField;
            set => current_serverField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool current_serverSpecified
        {
            get => current_serverFieldSpecified;
            set => current_serverFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public bool expedite_mode
        {
            get => expedite_modeField;
            set => expedite_modeField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool expedite_modeSpecified
        {
            get => expedite_modeFieldSpecified;
            set => expedite_modeFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public bool tiebreak
        {
            get => tiebreakField;
            set => tiebreakField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool tiebreakSpecified
        {
            get => tiebreakFieldSpecified;
            set => tiebreakFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int home_suspend
        {
            get => home_suspendField;
            set => home_suspendField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool home_suspendSpecified
        {
            get => home_suspendFieldSpecified;
            set => home_suspendFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int away_suspend
        {
            get => away_suspendField;
            set => away_suspendField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool away_suspendSpecified
        {
            get => away_suspendFieldSpecified;
            set => away_suspendFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int balls
        {
            get => ballsField;
            set => ballsField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool ballsSpecified
        {
            get => ballsFieldSpecified;
            set => ballsFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int strikes
        {
            get => strikesField;
            set => strikesField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool strikesSpecified
        {
            get => strikesFieldSpecified;
            set => strikesFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int outs
        {
            get => outsField;
            set => outsField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool outsSpecified
        {
            get => outsFieldSpecified;
            set => outsFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string bases
        {
            get => basesField;
            set => basesField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int home_batter
        {
            get => home_batterField;
            set => home_batterField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool home_batterSpecified
        {
            get => home_batterFieldSpecified;
            set => home_batterFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int away_batter
        {
            get => away_batterField;
            set => away_batterField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool away_batterSpecified
        {
            get => away_batterFieldSpecified;
            set => away_batterFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int possession
        {
            get => possessionField;
            set => possessionField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool possessionSpecified
        {
            get => possessionFieldSpecified;
            set => possessionFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int position
        {
            get => positionField;
            set => positionField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool positionSpecified
        {
            get => positionFieldSpecified;
            set => positionFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int @try
        {
            get => tryField;
            set => tryField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool trySpecified
        {
            get => tryFieldSpecified;
            set => tryFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int yards
        {
            get => yardsField;
            set => yardsField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool yardsSpecified
        {
            get => yardsFieldSpecified;
            set => yardsFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int @throw
        {
            get => throwField;
            set => throwField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool throwSpecified
        {
            get => throwFieldSpecified;
            set => throwFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int visit
        {
            get => visitField;
            set => visitField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool visitSpecified
        {
            get => visitFieldSpecified;
            set => visitFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int remaining_reds
        {
            get => remaining_redsField;
            set => remaining_redsField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool remaining_redsSpecified
        {
            get => remaining_redsFieldSpecified;
            set => remaining_redsFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int delivery
        {
            get => deliveryField;
            set => deliveryField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool deliverySpecified
        {
            get => deliveryFieldSpecified;
            set => deliveryFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int home_remaining_bowls
        {
            get => home_remaining_bowlsField;
            set => home_remaining_bowlsField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool home_remaining_bowlsSpecified
        {
            get => home_remaining_bowlsFieldSpecified;
            set => home_remaining_bowlsFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int away_remaining_bowls
        {
            get => away_remaining_bowlsField;
            set => away_remaining_bowlsField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool away_remaining_bowlsSpecified
        {
            get => away_remaining_bowlsFieldSpecified;
            set => away_remaining_bowlsFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int current_end
        {
            get => current_endField;
            set => current_endField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool current_endSpecified
        {
            get => current_endFieldSpecified;
            set => current_endFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int innings
        {
            get => inningsField;
            set => inningsField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool inningsSpecified
        {
            get => inningsFieldSpecified;
            set => inningsFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int over
        {
            get => overField;
            set => overField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool overSpecified
        {
            get => overFieldSpecified;
            set => overFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int home_penalty_runs
        {
            get => home_penalty_runsField;
            set => home_penalty_runsField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool home_penalty_runsSpecified
        {
            get => home_penalty_runsFieldSpecified;
            set => home_penalty_runsFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int away_penalty_runs
        {
            get => away_penalty_runsField;
            set => away_penalty_runsField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool away_penalty_runsSpecified
        {
            get => away_penalty_runsFieldSpecified;
            set => away_penalty_runsFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int home_dismissals
        {
            get => home_dismissalsField;
            set => home_dismissalsField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool home_dismissalsSpecified
        {
            get => home_dismissalsFieldSpecified;
            set => home_dismissalsFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int away_dismissals
        {
            get => away_dismissalsField;
            set => away_dismissalsField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool away_dismissalsSpecified
        {
            get => away_dismissalsFieldSpecified;
            set => away_dismissalsFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int current_ct_team
        {
            get => current_ct_teamField;
            set => current_ct_teamField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool current_ct_teamSpecified
        {
            get => current_ct_teamFieldSpecified;
            set => current_ct_teamFieldSpecified = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    public class clockType
    {
        private string match_timeField;

        private string remaining_time_in_periodField;

        private string remaining_timeField;

        private string stoppage_time_announcedField;

        private string stoppage_timeField;

        private bool stoppedField;

        private bool stoppedFieldSpecified;

        /// <remarks />
        [XmlAttribute]
        public string match_time
        {
            get => match_timeField;
            set => match_timeField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string stoppage_time
        {
            get => stoppage_timeField;
            set => stoppage_timeField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string stoppage_time_announced
        {
            get => stoppage_time_announcedField;
            set => stoppage_time_announcedField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string remaining_time
        {
            get => remaining_timeField;
            set => remaining_timeField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string remaining_time_in_period
        {
            get => remaining_time_in_periodField;
            set => remaining_time_in_periodField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public bool stopped
        {
            get => stoppedField;
            set => stoppedField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool stoppedSpecified
        {
            get => stoppedFieldSpecified;
            set => stoppedFieldSpecified = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    public partial class market
    {
        private string extended_specifiersField;

        private int idField;

        private string specifiersField;

        private int void_reasonField;

        private bool void_reasonFieldSpecified;

        /// <remarks />
        [XmlAttribute]
        public int id
        {
            get => idField;
            set => idField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string specifiers
        {
            get => specifiersField;
            set => specifiersField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string extended_specifiers
        {
            get => extended_specifiersField;
            set => extended_specifiersField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int void_reason
        {
            get => void_reasonField;
            set => void_reasonField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool void_reasonSpecified
        {
            get => void_reasonFieldSpecified;
            set => void_reasonFieldSpecified = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    public partial class betSettlementMarket
    {
        private string extended_specifiersField;

        private int idField;

        private betSettlementMarketOutcome[] itemsField;

        private string resultField;

        private string specifiersField;

        private int void_reasonField;

        private bool void_reasonFieldSpecified;

        /// <remarks />
        [XmlElement("outcome")]
        public betSettlementMarketOutcome[] Items
        {
            get => itemsField;
            set => itemsField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int id
        {
            get => idField;
            set => idField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string specifiers
        {
            get => specifiersField;
            set => specifiersField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string extended_specifiers
        {
            get => extended_specifiersField;
            set => extended_specifiersField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int void_reason
        {
            get => void_reasonField;
            set => void_reasonField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool void_reasonSpecified
        {
            get => void_reasonFieldSpecified;
            set => void_reasonFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string result
        {
            get => resultField;
            set => resultField = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class betSettlementMarketOutcome
    {
        private double dead_heat_factorField;

        private bool dead_heat_factorFieldSpecified;

        private string idField;

        private int resultField;

        private double void_factorField;

        private bool void_factorFieldSpecified;

        /// <remarks />
        [XmlAttribute]
        public string id
        {
            get => idField;
            set => idField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int result
        {
            get => resultField;
            set => resultField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public double void_factor
        {
            get => void_factorField;
            set => void_factorField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool void_factorSpecified
        {
            get => void_factorFieldSpecified;
            set => void_factorFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public double dead_heat_factor
        {
            get => dead_heat_factorField;
            set => dead_heat_factorField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool dead_heat_factorSpecified
        {
            get => dead_heat_factorFieldSpecified;
            set => dead_heat_factorFieldSpecified = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    public class marketMetadata
    {
        private long next_betstopField;

        private bool next_betstopFieldSpecified;

        /// <remarks />
        [XmlAttribute]
        public long next_betstop
        {
            get => next_betstopField;
            set => next_betstopField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool next_betstopSpecified
        {
            get => next_betstopFieldSpecified;
            set => next_betstopFieldSpecified = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    public partial class oddsChangeMarket
    {
        private int cashout_statusField;

        private bool cashout_statusFieldSpecified;

        private string extended_specifiersField;

        private int favouriteField;

        private bool favouriteFieldSpecified;

        private int idField;

        private marketMetadata market_metadataField;

        private oddsChangeMarketOutcome[] outcomeField;

        private string specifiersField;

        private int statusField;

        private bool statusFieldSpecified;

        /// <remarks />
        public marketMetadata market_metadata
        {
            get => market_metadataField;
            set => market_metadataField = value;
        }

        /// <remarks />
        [XmlElement("outcome")]
        public oddsChangeMarketOutcome[] outcome
        {
            get => outcomeField;
            set => outcomeField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int id
        {
            get => idField;
            set => idField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string specifiers
        {
            get => specifiersField;
            set => specifiersField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string extended_specifiers
        {
            get => extended_specifiersField;
            set => extended_specifiersField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int favourite
        {
            get => favouriteField;
            set => favouriteField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool favouriteSpecified
        {
            get => favouriteFieldSpecified;
            set => favouriteFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int status
        {
            get => statusField;
            set => statusField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool statusSpecified
        {
            get => statusFieldSpecified;
            set => statusFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int cashout_status
        {
            get => cashout_statusField;
            set => cashout_statusField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool cashout_statusSpecified
        {
            get => cashout_statusFieldSpecified;
            set => cashout_statusFieldSpecified = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class oddsChangeMarketOutcome
    {
        private int activeField;

        private bool activeFieldSpecified;

        private string idField;

        private double oddsField;

        private bool oddsFieldSpecified;

        private double probabilitiesField;

        private bool probabilitiesFieldSpecified;

        private int teamField;

        private bool teamFieldSpecified;

        /// <remarks />
        [XmlAttribute]
        public string id
        {
            get => idField;
            set => idField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public double odds
        {
            get => oddsField;
            set => oddsField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool oddsSpecified
        {
            get => oddsFieldSpecified;
            set => oddsFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public double probabilities
        {
            get => probabilitiesField;
            set => probabilitiesField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool probabilitiesSpecified
        {
            get => probabilitiesFieldSpecified;
            set => probabilitiesFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int active
        {
            get => activeField;
            set => activeField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool activeSpecified
        {
            get => activeFieldSpecified;
            set => activeFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int team
        {
            get => teamField;
            set => teamField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool teamSpecified
        {
            get => teamFieldSpecified;
            set => teamFieldSpecified = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    public class oddsGenerationProperties
    {
        private double expected_supremacyField;

        private bool expected_supremacyFieldSpecified;

        private double expected_totalsField;

        private bool expected_totalsFieldSpecified;

        /// <remarks />
        [XmlAttribute]
        public double expected_totals
        {
            get => expected_totalsField;
            set => expected_totalsField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool expected_totalsSpecified
        {
            get => expected_totalsFieldSpecified;
            set => expected_totalsFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public double expected_supremacy
        {
            get => expected_supremacyField;
            set => expected_supremacyField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool expected_supremacySpecified
        {
            get => expected_supremacyFieldSpecified;
            set => expected_supremacyFieldSpecified = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    public class statisticsScoreType
    {
        private int awayField;

        private int homeField;

        /// <remarks />
        [XmlAttribute]
        public int home
        {
            get => homeField;
            set => homeField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int away
        {
            get => awayField;
            set => awayField = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    public class statisticsType
    {
        private statisticsScoreType cornersField;

        private statisticsScoreType red_cardsField;

        private statisticsScoreType yellow_cardsField;

        private statisticsScoreType yellow_red_cardsField;

        /// <remarks />
        public statisticsScoreType yellow_cards
        {
            get => yellow_cardsField;
            set => yellow_cardsField = value;
        }

        /// <remarks />
        public statisticsScoreType red_cards
        {
            get => red_cardsField;
            set => red_cardsField = value;
        }

        /// <remarks />
        public statisticsScoreType yellow_red_cards
        {
            get => yellow_red_cardsField;
            set => yellow_red_cardsField = value;
        }

        /// <remarks />
        public statisticsScoreType corners
        {
            get => cornersField;
            set => cornersField = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    public class resultType
    {
        private decimal away_scoreField;

        private decimal home_scoreField;

        private int match_status_codeField;

        /// <remarks />
        [XmlAttribute]
        public int match_status_code
        {
            get => match_status_codeField;
            set => match_status_codeField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public decimal home_score
        {
            get => home_scoreField;
            set => home_scoreField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public decimal away_score
        {
            get => away_scoreField;
            set => away_scoreField = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    public class periodScoreType
    {
        private decimal away_scoreField;

        private decimal home_scoreField;

        private int match_status_codeField;

        private int numberField;

        /// <remarks />
        [XmlAttribute]
        public int match_status_code
        {
            get => match_status_codeField;
            set => match_status_codeField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int number
        {
            get => numberField;
            set => numberField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public decimal home_score
        {
            get => home_scoreField;
            set => home_scoreField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public decimal away_score
        {
            get => away_scoreField;
            set => away_scoreField = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class odds_changeOdds
    {
        private int betstop_reasonField;

        private bool betstop_reasonFieldSpecified;

        private int betting_statusField;

        private bool betting_statusFieldSpecified;

        private oddsChangeMarket[] marketField;

        /// <remarks />
        [XmlElement("market")]
        public oddsChangeMarket[] market
        {
            get => marketField;
            set => marketField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int betting_status
        {
            get => betting_statusField;
            set => betting_statusField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool betting_statusSpecified
        {
            get => betting_statusFieldSpecified;
            set => betting_statusFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int betstop_reason
        {
            get => betstop_reasonField;
            set => betstop_reasonField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool betstop_reasonSpecified
        {
            get => betstop_reasonFieldSpecified;
            set => betstop_reasonFieldSpecified = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class bet_settlement
    {
        private int certaintyField;

        private string event_idField;

        private betSettlementMarket[] outcomesField;

        private int productField;

        private long request_idField;

        private bool request_idFieldSpecified;

        private long timestampField;

        /// <remarks />
        [XmlArrayItem("market", IsNullable = false)]
        public betSettlementMarket[] outcomes
        {
            get => outcomesField;
            set => outcomesField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int product
        {
            get => productField;
            set => productField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string event_id
        {
            get => event_idField;
            set => event_idField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public long timestamp
        {
            get => timestampField;
            set => timestampField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public long request_id
        {
            get => request_idField;
            set => request_idField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool request_idSpecified
        {
            get => request_idFieldSpecified;
            set => request_idFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int certainty
        {
            get => certaintyField;
            set => certaintyField = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class rollback_bet_settlement
    {
        private string event_idField;

        private market[] marketField;

        private int productField;

        private long request_idField;

        private bool request_idFieldSpecified;

        private long timestampField;

        /// <remarks />
        [XmlElement("market")]
        public market[] market
        {
            get => marketField;
            set => marketField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int product
        {
            get => productField;
            set => productField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string event_id
        {
            get => event_idField;
            set => event_idField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public long timestamp
        {
            get => timestampField;
            set => timestampField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public long request_id
        {
            get => request_idField;
            set => request_idField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool request_idSpecified
        {
            get => request_idFieldSpecified;
            set => request_idFieldSpecified = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class bet_cancel
    {
        private long end_timeField;

        private bool end_timeFieldSpecified;

        private string event_idField;

        private market[] marketField;

        private int productField;

        private long request_idField;

        private bool request_idFieldSpecified;

        private long start_timeField;

        private bool start_timeFieldSpecified;

        private string superceded_byField;

        private long timestampField;

        /// <remarks />
        [XmlElement("market")]
        public market[] market
        {
            get => marketField;
            set => marketField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int product
        {
            get => productField;
            set => productField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string event_id
        {
            get => event_idField;
            set => event_idField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public long timestamp
        {
            get => timestampField;
            set => timestampField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public long request_id
        {
            get => request_idField;
            set => request_idField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool request_idSpecified
        {
            get => request_idFieldSpecified;
            set => request_idFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public long start_time
        {
            get => start_timeField;
            set => start_timeField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool start_timeSpecified
        {
            get => start_timeFieldSpecified;
            set => start_timeFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public long end_time
        {
            get => end_timeField;
            set => end_timeField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool end_timeSpecified
        {
            get => end_timeFieldSpecified;
            set => end_timeFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string superceded_by
        {
            get => superceded_byField;
            set => superceded_byField = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class rollback_bet_cancel
    {
        private long end_timeField;

        private bool end_timeFieldSpecified;

        private string event_idField;

        private market[] marketField;

        private int productField;

        private long request_idField;

        private bool request_idFieldSpecified;

        private long start_timeField;

        private bool start_timeFieldSpecified;

        private long timestampField;

        /// <remarks />
        [XmlElement("market")]
        public market[] market
        {
            get => marketField;
            set => marketField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int product
        {
            get => productField;
            set => productField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string event_id
        {
            get => event_idField;
            set => event_idField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public long timestamp
        {
            get => timestampField;
            set => timestampField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public long request_id
        {
            get => request_idField;
            set => request_idField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool request_idSpecified
        {
            get => request_idFieldSpecified;
            set => request_idFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public long start_time
        {
            get => start_timeField;
            set => start_timeField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool start_timeSpecified
        {
            get => start_timeFieldSpecified;
            set => start_timeFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public long end_time
        {
            get => end_timeField;
            set => end_timeField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool end_timeSpecified
        {
            get => end_timeFieldSpecified;
            set => end_timeFieldSpecified = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class alive
    {
        private int productField;

        private int subscribedField;

        private long timestampField;

        /// <remarks />
        [XmlAttribute]
        public int product
        {
            get => productField;
            set => productField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public long timestamp
        {
            get => timestampField;
            set => timestampField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int subscribed
        {
            get => subscribedField;
            set => subscribedField = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class snapshot_complete
    {
        private int productField;

        private long request_idField;

        private long timestampField;

        /// <remarks />
        [XmlAttribute]
        public long request_id
        {
            get => request_idField;
            set => request_idField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int product
        {
            get => productField;
            set => productField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public long timestamp
        {
            get => timestampField;
            set => timestampField = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class fixture_change
    {
        private int change_typeField;

        private bool change_typeFieldSpecified;

        private string event_idField;

        private long next_live_timeField;

        private bool next_live_timeFieldSpecified;

        private int productField;

        private long request_idField;

        private bool request_idFieldSpecified;

        private long start_timeField;

        private long timestampField;

        /// <remarks />
        [XmlAttribute]
        public int product
        {
            get => productField;
            set => productField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string event_id
        {
            get => event_idField;
            set => event_idField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public long timestamp
        {
            get => timestampField;
            set => timestampField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public long request_id
        {
            get => request_idField;
            set => request_idField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool request_idSpecified
        {
            get => request_idFieldSpecified;
            set => request_idFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int change_type
        {
            get => change_typeField;
            set => change_typeField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool change_typeSpecified
        {
            get => change_typeFieldSpecified;
            set => change_typeFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public long start_time
        {
            get => start_timeField;
            set => start_timeField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public long next_live_time
        {
            get => next_live_timeField;
            set => next_live_timeField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool next_live_timeSpecified
        {
            get => next_live_timeFieldSpecified;
            set => next_live_timeFieldSpecified = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class bet_stop
    {
        private string event_idField;

        private string groupsField;

        private int market_statusField;

        private bool market_statusFieldSpecified;

        private int productField;

        private long request_idField;

        private bool request_idFieldSpecified;

        private long timestampField;

        /// <remarks />
        [XmlAttribute]
        public int product
        {
            get => productField;
            set => productField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string event_id
        {
            get => event_idField;
            set => event_idField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public long timestamp
        {
            get => timestampField;
            set => timestampField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public long request_id
        {
            get => request_idField;
            set => request_idField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool request_idSpecified
        {
            get => request_idFieldSpecified;
            set => request_idFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string groups
        {
            get => groupsField;
            set => groupsField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int market_status
        {
            get => market_statusField;
            set => market_statusField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool market_statusSpecified
        {
            get => market_statusFieldSpecified;
            set => market_statusFieldSpecified = value;
        }
    }
}