/*
* Copyright (C) Sportradar AG. See LICENSE for full license governing this code
*/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;
using Sportradar.OddsFeed.SDK.Messages.Feed;

namespace Sportradar.OddsFeed.SDK.Messages.REST
{
    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class cashout
    {
        private string event_idField;

        private cashoutOdds oddsField;

        private int productField;

        private long request_idField;

        private bool request_idFieldSpecified;

        private restSportEventStatus sport_event_statusField;

        private long timestampField;

        /// <remarks />
        public restSportEventStatus sport_event_status
        {
            get => sport_event_statusField;
            set => sport_event_statusField = value;
        }

        /// <remarks />
        public cashoutOdds odds
        {
            get => oddsField;
            set => oddsField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int product
        {
            get => productField;
            set => productField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string event_id
        {
            get => event_idField;
            set => event_idField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public long timestamp
        {
            get => timestampField;
            set => timestampField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public long request_id
        {
            get => request_idField;
            set => request_idField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool request_idSpecified
        {
            get => request_idFieldSpecified;
            set => request_idFieldSpecified = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class cashoutOdds
    {
        private int betstop_reasonField;

        private bool betstop_reasonFieldSpecified;

        private int betting_statusField;

        private bool betting_statusFieldSpecified;

        private oddsChangeMarket[] marketField;

        /// <remarks />
        [XmlElement("market")]
        public oddsChangeMarket[] market
        {
            get => marketField;
            set => marketField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int betting_status
        {
            get => betting_statusField;
            set => betting_statusField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool betting_statusSpecified
        {
            get => betting_statusFieldSpecified;
            set => betting_statusFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int betstop_reason
        {
            get => betstop_reasonField;
            set => betstop_reasonField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool betstop_reasonSpecified
        {
            get => betstop_reasonFieldSpecified;
            set => betstop_reasonFieldSpecified = value;
        }
    }
}