/*
* Copyright (C) Sportradar AG. See LICENSE for full license governing this code
*/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

namespace Sportradar.OddsFeed.SDK.Messages.REST
{
    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class response
    {
        private string actionField;

        private string messageField;

        private response_code response_codeField;

        private bool response_codeFieldSpecified;

        /// <remarks />
        public string action
        {
            get => actionField;
            set => actionField = value;
        }

        /// <remarks />
        public string message
        {
            get => messageField;
            set => messageField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public response_code response_code
        {
            get => response_codeField;
            set => response_codeField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool response_codeSpecified
        {
            get => response_codeFieldSpecified;
            set => response_codeFieldSpecified = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    public enum response_code
    {
        /// <remarks />
        OK,

        /// <remarks />
        CREATED,

        /// <remarks />
        ACCEPTED,

        /// <remarks />
        FORBIDDEN,

        /// <remarks />
        NOT_FOUND,

        /// <remarks />
        CONFLICT,

        /// <remarks />
        SERVICE_UNAVAILABLE,

        /// <remarks />
        NOT_IMPLEMENTED,

        /// <remarks />
        MOVED_PERMANENTLY,

        /// <remarks />
        BAD_REQUEST
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    public class desc_variant
    {
        private string idField;

        private variant_mappingsMapping[] mappingsField;

        private desc_variant_outcomesOutcome[] outcomesField;

        /// <remarks />
        [XmlArrayItem("outcome", IsNullable = false)]
        public desc_variant_outcomesOutcome[] outcomes
        {
            get => outcomesField;
            set => outcomesField = value;
        }

        /// <remarks />
        [XmlArrayItem("mapping", IsNullable = false)]
        public variant_mappingsMapping[] mappings
        {
            get => mappingsField;
            set => mappingsField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string id
        {
            get => idField;
            set => idField = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class desc_variant_outcomesOutcome
    {
        private string idField;

        private string nameField;

        /// <remarks />
        [XmlAttribute]
        public string id
        {
            get => idField;
            set => idField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string name
        {
            get => nameField;
            set => nameField = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class variant_mappingsMapping
    {
        private variant_mappingsMappingMapping_outcome[] mapping_outcomeField;

        private string market_idField;

        private int product_idField;

        private string product_idsField;

        private string product_market_idField;

        private string sov_templateField;

        private string sport_idField;

        private string valid_forField;

        /// <remarks />
        [XmlElement("mapping_outcome")]
        public variant_mappingsMappingMapping_outcome[] mapping_outcome
        {
            get => mapping_outcomeField;
            set => mapping_outcomeField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int product_id
        {
            get => product_idField;
            set => product_idField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string product_ids
        {
            get => product_idsField;
            set => product_idsField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string sport_id
        {
            get => sport_idField;
            set => sport_idField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string market_id
        {
            get => market_idField;
            set => market_idField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string sov_template
        {
            get => sov_templateField;
            set => sov_templateField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string valid_for
        {
            get => valid_forField;
            set => valid_forField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string product_market_id
        {
            get => product_market_idField;
            set => product_market_idField = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class variant_mappingsMappingMapping_outcome
    {
        private string outcome_idField;

        private string product_outcome_idField;

        private string product_outcome_nameField;

        /// <remarks />
        [XmlAttribute]
        public string outcome_id
        {
            get => outcome_idField;
            set => outcome_idField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string product_outcome_id
        {
            get => product_outcome_idField;
            set => product_outcome_idField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string product_outcome_name
        {
            get => product_outcome_nameField;
            set => product_outcome_nameField = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    public class producer
    {
        private bool activeField;

        private string api_urlField;

        private string descriptionField;

        private long idField;

        private string nameField;

        private string scopeField;

        private int stateful_recovery_window_in_minutesField;

        /// <remarks />
        [XmlAttribute]
        public long id
        {
            get => idField;
            set => idField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string name
        {
            get => nameField;
            set => nameField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string description
        {
            get => descriptionField;
            set => descriptionField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string api_url
        {
            get => api_urlField;
            set => api_urlField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public bool active
        {
            get => activeField;
            set => activeField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string scope
        {
            get => scopeField;
            set => scopeField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int stateful_recovery_window_in_minutes
        {
            get => stateful_recovery_window_in_minutesField;
            set => stateful_recovery_window_in_minutesField = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    public class desc_void_reason
    {
        private string descriptionField;

        private long idField;

        /// <remarks />
        [XmlAttribute]
        public long id
        {
            get => idField;
            set => idField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string description
        {
            get => descriptionField;
            set => descriptionField = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    public class desc_match_status
    {
        private string descriptionField;

        private long idField;

        private int period_numberField;

        private bool period_numberFieldSpecified;

        private desc_match_statusSports sportsField;

        /// <remarks />
        public desc_match_statusSports sports
        {
            get => sportsField;
            set => sportsField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public long id
        {
            get => idField;
            set => idField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string description
        {
            get => descriptionField;
            set => descriptionField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int period_number
        {
            get => period_numberField;
            set => period_numberField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool period_numberSpecified
        {
            get => period_numberFieldSpecified;
            set => period_numberFieldSpecified = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class desc_match_statusSports
    {
        private bool allField;

        private desc_match_statusSportsSport[] sportField;

        public desc_match_statusSports()
        {
            allField = false;
        }

        /// <remarks />
        [XmlElement("sport")]
        public desc_match_statusSportsSport[] sport
        {
            get => sportField;
            set => sportField = value;
        }

        /// <remarks />
        [XmlAttribute]
        [DefaultValue(false)]
        public bool all
        {
            get => allField;
            set => allField = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class desc_match_statusSportsSport
    {
        private string idField;

        /// <remarks />
        [XmlAttribute]
        public string id
        {
            get => idField;
            set => idField = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    public class desc_betting_status
    {
        private string descriptionField;

        private long idField;

        /// <remarks />
        [XmlAttribute]
        public long id
        {
            get => idField;
            set => idField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string description
        {
            get => descriptionField;
            set => descriptionField = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    public class desc_outcome_reason
    {
        private string descriptionField;

        private long idField;

        /// <remarks />
        [XmlAttribute]
        public long id
        {
            get => idField;
            set => idField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string description
        {
            get => descriptionField;
            set => descriptionField = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    public class desc_betstop_reason
    {
        private string descriptionField;

        private long idField;

        /// <remarks />
        [XmlAttribute]
        public long id
        {
            get => idField;
            set => idField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string description
        {
            get => descriptionField;
            set => descriptionField = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    public class desc_market
    {
        private attributesAttribute[] attributesField;

        private string descriptionField;

        private string groupsField;

        private int idField;

        private string includes_outcomes_of_typeField;

        private mappingsMapping[] mappingsField;

        private string nameField;

        private string outcome_typeField;

        private desc_outcomesOutcome[] outcomesField;

        private desc_specifiersSpecifier[] specifiersField;

        private string variantField;

        /// <remarks />
        [XmlArrayItem("outcome", IsNullable = false)]
        public desc_outcomesOutcome[] outcomes
        {
            get => outcomesField;
            set => outcomesField = value;
        }

        /// <remarks />
        [XmlArrayItem("specifier", IsNullable = false)]
        public desc_specifiersSpecifier[] specifiers
        {
            get => specifiersField;
            set => specifiersField = value;
        }

        /// <remarks />
        [XmlArrayItem("mapping", IsNullable = false)]
        public mappingsMapping[] mappings
        {
            get => mappingsField;
            set => mappingsField = value;
        }

        /// <remarks />
        [XmlArrayItem("attribute", IsNullable = false)]
        public attributesAttribute[] attributes
        {
            get => attributesField;
            set => attributesField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int id
        {
            get => idField;
            set => idField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string name
        {
            get => nameField;
            set => nameField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string groups
        {
            get => groupsField;
            set => groupsField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string description
        {
            get => descriptionField;
            set => descriptionField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string includes_outcomes_of_type
        {
            get => includes_outcomes_of_typeField;
            set => includes_outcomes_of_typeField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string variant
        {
            get => variantField;
            set => variantField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string outcome_type
        {
            get => outcome_typeField;
            set => outcome_typeField = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class desc_outcomesOutcome
    {
        private string descriptionField;

        private string idField;

        private string nameField;

        /// <remarks />
        [XmlAttribute]
        public string id
        {
            get => idField;
            set => idField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string name
        {
            get => nameField;
            set => nameField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string description
        {
            get => descriptionField;
            set => descriptionField = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class desc_specifiersSpecifier
    {
        private string descriptionField;

        private string nameField;

        private string typeField;

        /// <remarks />
        [XmlAttribute]
        public string name
        {
            get => nameField;
            set => nameField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string type
        {
            get => typeField;
            set => typeField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string description
        {
            get => descriptionField;
            set => descriptionField = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class mappingsMapping
    {
        private mappingsMappingMapping_outcome[] mapping_outcomeField;

        private string market_idField;

        private int product_idField;

        private string product_idsField;

        private string sov_templateField;

        private string sport_idField;

        private string valid_forField;

        /// <remarks />
        [XmlElement("mapping_outcome")]
        public mappingsMappingMapping_outcome[] mapping_outcome
        {
            get => mapping_outcomeField;
            set => mapping_outcomeField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int product_id
        {
            get => product_idField;
            set => product_idField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string product_ids
        {
            get => product_idsField;
            set => product_idsField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string sport_id
        {
            get => sport_idField;
            set => sport_idField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string market_id
        {
            get => market_idField;
            set => market_idField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string sov_template
        {
            get => sov_templateField;
            set => sov_templateField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string valid_for
        {
            get => valid_forField;
            set => valid_forField = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class mappingsMappingMapping_outcome
    {
        private string outcome_idField;

        private string product_outcome_idField;

        private string product_outcome_nameField;

        /// <remarks />
        [XmlAttribute]
        public string outcome_id
        {
            get => outcome_idField;
            set => outcome_idField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string product_outcome_id
        {
            get => product_outcome_idField;
            set => product_outcome_idField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string product_outcome_name
        {
            get => product_outcome_nameField;
            set => product_outcome_nameField = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class attributesAttribute
    {
        private string descriptionField;

        private string nameField;

        /// <remarks />
        [XmlAttribute]
        public string name
        {
            get => nameField;
            set => nameField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string description
        {
            get => descriptionField;
            set => descriptionField = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class bookmaker_details
    {
        private int bookmaker_idField;

        private bool bookmaker_idFieldSpecified;

        private DateTime expire_atField;

        private bool expire_atFieldSpecified;

        private string messageField;

        private response_code response_codeField;

        private bool response_codeFieldSpecified;

        private string virtual_hostField;

        /// <remarks />
        public string message
        {
            get => messageField;
            set => messageField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public response_code response_code
        {
            get => response_codeField;
            set => response_codeField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool response_codeSpecified
        {
            get => response_codeFieldSpecified;
            set => response_codeFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public DateTime expire_at
        {
            get => expire_atField;
            set => expire_atField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool expire_atSpecified
        {
            get => expire_atFieldSpecified;
            set => expire_atFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public int bookmaker_id
        {
            get => bookmaker_idField;
            set => bookmaker_idField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool bookmaker_idSpecified
        {
            get => bookmaker_idFieldSpecified;
            set => bookmaker_idFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string virtual_host
        {
            get => virtual_hostField;
            set => virtual_hostField = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class market_descriptions
    {
        private string locationField;

        private desc_market[] marketField;

        private response_code response_codeField;

        private bool response_codeFieldSpecified;

        /// <remarks />
        [XmlElement("market")]
        public desc_market[] market
        {
            get => marketField;
            set => marketField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public response_code response_code
        {
            get => response_codeField;
            set => response_codeField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool response_codeSpecified
        {
            get => response_codeFieldSpecified;
            set => response_codeFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string location
        {
            get => locationField;
            set => locationField = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public class betstop_reasons_descriptions
    {
        private desc_betstop_reason[] betstop_reasonField;

        private string locationField;

        private response_code response_codeField;

        private bool response_codeFieldSpecified;

        /// <remarks />
        [XmlElement("betstop_reason")]
        public desc_betstop_reason[] betstop_reason
        {
            get => betstop_reasonField;
            set => betstop_reasonField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public response_code response_code
        {
            get => response_codeField;
            set => response_codeField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool response_codeSpecified
        {
            get => response_codeFieldSpecified;
            set => response_codeFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string location
        {
            get => locationField;
            set => locationField = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public class outcome_reasons_descriptions
    {
        private string locationField;

        private desc_outcome_reason[] outcome_reasonField;

        private response_code response_codeField;

        private bool response_codeFieldSpecified;

        /// <remarks />
        [XmlElement("outcome_reason")]
        public desc_outcome_reason[] outcome_reason
        {
            get => outcome_reasonField;
            set => outcome_reasonField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public response_code response_code
        {
            get => response_codeField;
            set => response_codeField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool response_codeSpecified
        {
            get => response_codeFieldSpecified;
            set => response_codeFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string location
        {
            get => locationField;
            set => locationField = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public class betting_status_descriptions
    {
        private desc_betting_status[] betting_statusField;

        private string locationField;

        private response_code response_codeField;

        private bool response_codeFieldSpecified;

        /// <remarks />
        [XmlElement("betting_status")]
        public desc_betting_status[] betting_status
        {
            get => betting_statusField;
            set => betting_statusField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public response_code response_code
        {
            get => response_codeField;
            set => response_codeField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool response_codeSpecified
        {
            get => response_codeFieldSpecified;
            set => response_codeFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string location
        {
            get => locationField;
            set => locationField = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public class match_status_descriptions
    {
        private string locationField;

        private desc_match_status[] match_statusField;

        private response_code response_codeField;

        private bool response_codeFieldSpecified;

        /// <remarks />
        [XmlElement("match_status")]
        public desc_match_status[] match_status
        {
            get => match_statusField;
            set => match_statusField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public response_code response_code
        {
            get => response_codeField;
            set => response_codeField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool response_codeSpecified
        {
            get => response_codeFieldSpecified;
            set => response_codeFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string location
        {
            get => locationField;
            set => locationField = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public class void_reasons_descriptions
    {
        private string locationField;

        private response_code response_codeField;

        private bool response_codeFieldSpecified;

        private desc_void_reason[] void_reasonField;

        /// <remarks />
        [XmlElement("void_reason")]
        public desc_void_reason[] void_reason
        {
            get => void_reasonField;
            set => void_reasonField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public response_code response_code
        {
            get => response_codeField;
            set => response_codeField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool response_codeSpecified
        {
            get => response_codeFieldSpecified;
            set => response_codeFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string location
        {
            get => locationField;
            set => locationField = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class producers
    {
        private string locationField;

        private producer[] producerField;

        private response_code response_codeField;

        private bool response_codeFieldSpecified;

        /// <remarks />
        [XmlElement("producer")]
        public producer[] producer
        {
            get => producerField;
            set => producerField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public response_code response_code
        {
            get => response_codeField;
            set => response_codeField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool response_codeSpecified
        {
            get => response_codeFieldSpecified;
            set => response_codeFieldSpecified = value;
        }

        /// <remarks />
        [XmlAttribute]
        public string location
        {
            get => locationField;
            set => locationField = value;
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.6.1055.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class variant_descriptions
    {
        private response_code response_codeField;

        private bool response_codeFieldSpecified;

        private desc_variant[] variantField;

        /// <remarks />
        [XmlElement("variant")]
        public desc_variant[] variant
        {
            get => variantField;
            set => variantField = value;
        }

        /// <remarks />
        [XmlAttribute]
        public response_code response_code
        {
            get => response_codeField;
            set => response_codeField = value;
        }

        /// <remarks />
        [XmlIgnore]
        public bool response_codeSpecified
        {
            get => response_codeFieldSpecified;
            set => response_codeFieldSpecified = value;
        }
    }
}